[build]
  command = "npm install --legacy-peer-deps && npx prisma generate && npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--legacy-peer-deps"
  SECRETS_SCAN_OMIT_KEYS = "NEXT_PUBLIC_BASE_URL,STORE_PHONE,BITESHIP_ORIGIN_AREA_ID,NEXT_PUBLIC_SUPABASE_URL,NEXT_PUBLIC_SUPABASE_PUBLISHABLE_DEFAULT_KEY"

[[plugins]]
  package = "@netlify/plugin-nextjs"